name: CD - Dev

on:
  push:
    branches: [ dev ]

jobs:
  cd:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: dev

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/dev.key
          chmod 600 ~/.ssh/dev.key
          cat >>~/.ssh/config <<END
          Host dev
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/dev.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_DEV_USER }}
          SSH_KEY: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_DEV_HOST }}

      - name: Stop the server
        run: ssh dev 'docker-compose stop'

      #- name: Remove container and image
      #  run: ssh dev 'docker container rm followers && docker image rm georgesstefan/jibber-jabber-follows-dev'

      - name: Copy files
        run: scp ... 

      - name: Start the server
        if: ${{ always() }}
        run: ssh dev 'docker-compose up -d > /dev/null 2>&1'
