name: CD - Dev

on:
  push:
    branches: [ main ]

jobs:
  cd:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/prod.key
          chmod 600 ~/.ssh/prod.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/prod.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_PROD_USER }}
          SSH_KEY: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_PROD_HOST }}

      - name: Stop the server
        run: ssh prod 'docker-compose stop'
        
      - name: Copy docker-compose.yml via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          port: 22
          key: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "~"
      
      - name: Copy nginx config via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          port: 22
          key: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          source: "nginx/default.conf"
          target: "~/nginx/"
          
      - name: Copy keycloak config via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_PROD_HOST }}
          username: ${{ secrets.SSH_PROD_USER }}
          port: 22
          key: ${{ secrets.SSH_PROD_PRIVATE_KEY }}
          source: "keycloak/register.ftl,keycloak/theme.properties"
          target: "~/keycloak/"

      - name: Start the server
        if: ${{ always() }}
        run: ssh prod 'docker-compose up -d > /dev/null 2>&1'
